name: untitled1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  logger: ^2.4.0
  flutter_iconpicker: ^4.0.0
  provider: ^6.1.2

  # New dependencies added
  flutter_local_notifications: ^15.1.3 # or a newer version if available
  timezone: ^0.9.0
  intl: ^0.18.0 # For internationalization, date formatting, and localization support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

